/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 123
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 12
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_fn = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_DASH_GT = 5,
  anon_sym_COLON = 6,
  anon_sym_let = 7,
  anon_sym_EQ = 8,
  anon_sym_COMMA = 9,
  sym_type_u8 = 10,
  sym_type_u16 = 11,
  sym_type_u32 = 12,
  sym_type_u64 = 13,
  sym_type_i8 = 14,
  sym_type_i16 = 15,
  sym_type_i32 = 16,
  sym_type_i64 = 17,
  sym_type_f32 = 18,
  sym_type_f64 = 19,
  sym_type_bool = 20,
  sym_number = 21,
  anon_sym_DQUOTE = 22,
  aux_sym_string_token1 = 23,
  anon_sym_DQUOTE_DQUOTE = 24,
  sym_identifier = 25,
  sym_newline = 26,
  sym_indent = 27,
  sym_dedent = 28,
  sym_source_file = 29,
  sym__statement = 30,
  sym_function_definition = 31,
  sym_let_statement = 32,
  sym_parameters = 33,
  sym_parameter = 34,
  sym_type_annotation = 35,
  sym_expression = 36,
  sym_call_expression = 37,
  sym_arguments = 38,
  sym_string = 39,
  aux_sym_source_file_repeat1 = 40,
  aux_sym_parameters_repeat1 = 41,
  aux_sym_arguments_repeat1 = 42,
  aux_sym_string_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_COLON] = ":",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [sym_type_u8] = "type_u8",
  [sym_type_u16] = "type_u16",
  [sym_type_u32] = "type_u32",
  [sym_type_u64] = "type_u64",
  [sym_type_i8] = "type_i8",
  [sym_type_i16] = "type_i16",
  [sym_type_i32] = "type_i32",
  [sym_type_i64] = "type_i64",
  [sym_type_f32] = "type_f32",
  [sym_type_f64] = "type_f64",
  [sym_type_bool] = "type_bool",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_DQUOTE_DQUOTE] = "\"\"",
  [sym_identifier] = "identifier",
  [sym_newline] = "newline",
  [sym_indent] = "indent",
  [sym_dedent] = "dedent",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_function_definition] = "function_definition",
  [sym_let_statement] = "let_statement",
  [sym_parameters] = "parameters",
  [sym_parameter] = "parameter",
  [sym_type_annotation] = "type_annotation",
  [sym_expression] = "expression",
  [sym_call_expression] = "call_expression",
  [sym_arguments] = "arguments",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_arguments_repeat1] = "arguments_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_type_u8] = sym_type_u8,
  [sym_type_u16] = sym_type_u16,
  [sym_type_u32] = sym_type_u32,
  [sym_type_u64] = sym_type_u64,
  [sym_type_i8] = sym_type_i8,
  [sym_type_i16] = sym_type_i16,
  [sym_type_i32] = sym_type_i32,
  [sym_type_i64] = sym_type_i64,
  [sym_type_f32] = sym_type_f32,
  [sym_type_f64] = sym_type_f64,
  [sym_type_bool] = sym_type_bool,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_DQUOTE_DQUOTE] = anon_sym_DQUOTE_DQUOTE,
  [sym_identifier] = sym_identifier,
  [sym_newline] = sym_newline,
  [sym_indent] = sym_indent,
  [sym_dedent] = sym_dedent,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_function_definition] = sym_function_definition,
  [sym_let_statement] = sym_let_statement,
  [sym_parameters] = sym_parameters,
  [sym_parameter] = sym_parameter,
  [sym_type_annotation] = sym_type_annotation,
  [sym_expression] = sym_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_arguments] = sym_arguments,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_arguments_repeat1] = aux_sym_arguments_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_type_u8] = {
    .visible = true,
    .named = true,
  },
  [sym_type_u16] = {
    .visible = true,
    .named = true,
  },
  [sym_type_u32] = {
    .visible = true,
    .named = true,
  },
  [sym_type_u64] = {
    .visible = true,
    .named = true,
  },
  [sym_type_i8] = {
    .visible = true,
    .named = true,
  },
  [sym_type_i16] = {
    .visible = true,
    .named = true,
  },
  [sym_type_i32] = {
    .visible = true,
    .named = true,
  },
  [sym_type_i64] = {
    .visible = true,
    .named = true,
  },
  [sym_type_f32] = {
    .visible = true,
    .named = true,
  },
  [sym_type_f64] = {
    .visible = true,
    .named = true,
  },
  [sym_type_bool] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_indent] = {
    .visible = true,
    .named = true,
  },
  [sym_dedent] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_type_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_arguments] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 3,
  [7] = 2,
  [8] = 4,
  [9] = 9,
  [10] = 9,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 12,
  [21] = 21,
  [22] = 13,
  [23] = 14,
  [24] = 15,
  [25] = 16,
  [26] = 17,
  [27] = 18,
  [28] = 19,
  [29] = 21,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 32,
  [34] = 30,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 37,
  [39] = 39,
  [40] = 40,
  [41] = 35,
  [42] = 39,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 47,
  [53] = 53,
  [54] = 54,
  [55] = 51,
  [56] = 43,
  [57] = 57,
  [58] = 44,
  [59] = 48,
  [60] = 60,
  [61] = 46,
  [62] = 62,
  [63] = 49,
  [64] = 64,
  [65] = 64,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 45,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 76,
  [79] = 74,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 84,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 82,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 72,
  [94] = 94,
  [95] = 88,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 70,
  [100] = 100,
  [101] = 87,
  [102] = 94,
  [103] = 103,
  [104] = 104,
  [105] = 98,
  [106] = 91,
  [107] = 81,
  [108] = 83,
  [109] = 97,
  [110] = 92,
  [111] = 69,
  [112] = 68,
  [113] = 113,
  [114] = 100,
  [115] = 86,
  [116] = 116,
  [117] = 116,
  [118] = 103,
  [119] = 71,
  [120] = 80,
  [121] = 90,
  [122] = 96,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      ADVANCE_MAP(
        '"', 58,
        '(', 26,
        ')', 27,
        ',', 32,
        '-', 16,
        '/', 4,
        ':', 29,
        '=', 31,
        'b', 20,
        'f', 10,
        'i', 5,
        'l', 17,
        'u', 6,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '/') ADVANCE(60);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0) ADVANCE(59);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(57);
      if (lookahead == ')') ADVANCE(27);
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'b') ADVANCE(76);
      if (lookahead == 'f') ADVANCE(68);
      if (lookahead == 'i') ADVANCE(63);
      if (lookahead == 'u') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(24);
      END_STATE();
    case 5:
      if (lookahead == '1') ADVANCE(14);
      if (lookahead == '3') ADVANCE(8);
      if (lookahead == '6') ADVANCE(12);
      if (lookahead == '8') ADVANCE(41);
      END_STATE();
    case 6:
      if (lookahead == '1') ADVANCE(15);
      if (lookahead == '3') ADVANCE(9);
      if (lookahead == '6') ADVANCE(13);
      if (lookahead == '8') ADVANCE(33);
      END_STATE();
    case 7:
      if (lookahead == '2') ADVANCE(49);
      END_STATE();
    case 8:
      if (lookahead == '2') ADVANCE(45);
      END_STATE();
    case 9:
      if (lookahead == '2') ADVANCE(37);
      END_STATE();
    case 10:
      if (lookahead == '3') ADVANCE(7);
      if (lookahead == '6') ADVANCE(11);
      if (lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 11:
      if (lookahead == '4') ADVANCE(51);
      END_STATE();
    case 12:
      if (lookahead == '4') ADVANCE(47);
      END_STATE();
    case 13:
      if (lookahead == '4') ADVANCE(39);
      END_STATE();
    case 14:
      if (lookahead == '6') ADVANCE(43);
      END_STATE();
    case 15:
      if (lookahead == '6') ADVANCE(35);
      END_STATE();
    case 16:
      if (lookahead == '>') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(53);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_type_u8);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_type_u8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_type_u16);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_type_u16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_type_u32);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_type_u32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_type_u64);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_type_u64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_type_i8);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_type_i8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_type_i16);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_type_i16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_type_i32);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_type_i32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_type_i64);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_type_i64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_type_f32);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_type_f32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_type_f64);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_type_f64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_type_bool);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_type_bool);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead == '"') ADVANCE(62);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(24);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(60);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(59);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '1') ADVANCE(72);
      if (lookahead == '3') ADVANCE(66);
      if (lookahead == '6') ADVANCE(70);
      if (lookahead == '8') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '1') ADVANCE(73);
      if (lookahead == '3') ADVANCE(67);
      if (lookahead == '6') ADVANCE(71);
      if (lookahead == '8') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '2') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '3') ADVANCE(65);
      if (lookahead == '6') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '4') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '6') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '6') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 2},
  [18] = {.lex_state = 0, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 2},
  [20] = {.lex_state = 0, .external_lex_state = 2},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 0, .external_lex_state = 2},
  [23] = {.lex_state = 0, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 2},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 0, .external_lex_state = 2},
  [44] = {.lex_state = 0, .external_lex_state = 2},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0, .external_lex_state = 2},
  [47] = {.lex_state = 0, .external_lex_state = 2},
  [48] = {.lex_state = 0, .external_lex_state = 2},
  [49] = {.lex_state = 0, .external_lex_state = 2},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0, .external_lex_state = 2},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0, .external_lex_state = 3},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0, .external_lex_state = 3},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0, .external_lex_state = 3},
  [84] = {.lex_state = 0, .external_lex_state = 3},
  [85] = {.lex_state = 0, .external_lex_state = 3},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0, .external_lex_state = 4},
  [88] = {.lex_state = 0, .external_lex_state = 3},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 0, .external_lex_state = 3},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 0, .external_lex_state = 3},
  [94] = {.lex_state = 0, .external_lex_state = 4},
  [95] = {.lex_state = 0, .external_lex_state = 3},
  [96] = {.lex_state = 0, .external_lex_state = 4},
  [97] = {.lex_state = 0, .external_lex_state = 3},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0, .external_lex_state = 3},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0, .external_lex_state = 4},
  [102] = {.lex_state = 0, .external_lex_state = 4},
  [103] = {.lex_state = 0, .external_lex_state = 4},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0, .external_lex_state = 3},
  [107] = {.lex_state = 0, .external_lex_state = 3},
  [108] = {.lex_state = 0, .external_lex_state = 3},
  [109] = {.lex_state = 0, .external_lex_state = 3},
  [110] = {.lex_state = 2},
  [111] = {.lex_state = 0, .external_lex_state = 3},
  [112] = {.lex_state = 0, .external_lex_state = 3},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0, .external_lex_state = 4},
  [119] = {.lex_state = 0, .external_lex_state = 3},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 2},
  [122] = {.lex_state = 0, .external_lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_type_u8] = ACTIONS(1),
    [sym_type_u16] = ACTIONS(1),
    [sym_type_u32] = ACTIONS(1),
    [sym_type_u64] = ACTIONS(1),
    [sym_type_i8] = ACTIONS(1),
    [sym_type_i16] = ACTIONS(1),
    [sym_type_i32] = ACTIONS(1),
    [sym_type_i64] = ACTIONS(1),
    [sym_type_f32] = ACTIONS(1),
    [sym_type_f64] = ACTIONS(1),
    [sym_type_bool] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE_DQUOTE] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_indent] = ACTIONS(1),
    [sym_dedent] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(113),
    [sym__statement] = STATE(11),
    [sym_function_definition] = STATE(11),
    [sym_let_statement] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(98), 1,
      sym_type_annotation,
    ACTIONS(13), 12,
      sym_type_u8,
      sym_type_u16,
      sym_type_u32,
      sym_type_u64,
      sym_type_i8,
      sym_type_i16,
      sym_type_i32,
      sym_type_i64,
      sym_type_f32,
      sym_type_f64,
      sym_type_bool,
      sym_identifier,
  [21] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(115), 1,
      sym_type_annotation,
    ACTIONS(13), 12,
      sym_type_u8,
      sym_type_u16,
      sym_type_u32,
      sym_type_u64,
      sym_type_i8,
      sym_type_i16,
      sym_type_i32,
      sym_type_i64,
      sym_type_f32,
      sym_type_f64,
      sym_type_bool,
      sym_identifier,
  [42] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(100), 1,
      sym_type_annotation,
    ACTIONS(13), 12,
      sym_type_u8,
      sym_type_u16,
      sym_type_u32,
      sym_type_u64,
      sym_type_i8,
      sym_type_i16,
      sym_type_i32,
      sym_type_i64,
      sym_type_f32,
      sym_type_f64,
      sym_type_bool,
      sym_identifier,
  [63] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(66), 1,
      sym_type_annotation,
    ACTIONS(13), 12,
      sym_type_u8,
      sym_type_u16,
      sym_type_u32,
      sym_type_u64,
      sym_type_i8,
      sym_type_i16,
      sym_type_i32,
      sym_type_i64,
      sym_type_f32,
      sym_type_f64,
      sym_type_bool,
      sym_identifier,
  [84] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(86), 1,
      sym_type_annotation,
    ACTIONS(13), 12,
      sym_type_u8,
      sym_type_u16,
      sym_type_u32,
      sym_type_u64,
      sym_type_i8,
      sym_type_i16,
      sym_type_i32,
      sym_type_i64,
      sym_type_f32,
      sym_type_f64,
      sym_type_bool,
      sym_identifier,
  [105] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(105), 1,
      sym_type_annotation,
    ACTIONS(13), 12,
      sym_type_u8,
      sym_type_u16,
      sym_type_u32,
      sym_type_u64,
      sym_type_i8,
      sym_type_i16,
      sym_type_i32,
      sym_type_i64,
      sym_type_f32,
      sym_type_f64,
      sym_type_bool,
      sym_identifier,
  [126] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(114), 1,
      sym_type_annotation,
    ACTIONS(13), 12,
      sym_type_u8,
      sym_type_u16,
      sym_type_u32,
      sym_type_u64,
      sym_type_i8,
      sym_type_i16,
      sym_type_i32,
      sym_type_i64,
      sym_type_f32,
      sym_type_f64,
      sym_type_bool,
      sym_identifier,
  [147] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_RPAREN,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(50), 1,
      sym_expression,
    STATE(82), 1,
      sym_arguments,
    STATE(68), 2,
      sym_call_expression,
      sym_string,
  [173] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_RPAREN,
    STATE(50), 1,
      sym_expression,
    STATE(89), 1,
      sym_arguments,
    STATE(68), 2,
      sym_call_expression,
      sym_string,
  [199] = 5,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(11), 1,
      anon_sym_let,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      sym_comment,
    STATE(29), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [218] = 5,
    ACTIONS(29), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_let,
    ACTIONS(35), 1,
      sym_dedent,
    STATE(21), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [237] = 5,
    ACTIONS(31), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_let,
    ACTIONS(37), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_dedent,
    STATE(14), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [256] = 5,
    ACTIONS(29), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      sym_dedent,
    STATE(21), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [275] = 5,
    ACTIONS(31), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_let,
    ACTIONS(41), 1,
      sym_dedent,
    ACTIONS(43), 1,
      sym_comment,
    STATE(17), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [294] = 5,
    ACTIONS(31), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_let,
    ACTIONS(45), 1,
      sym_comment,
    ACTIONS(47), 1,
      sym_dedent,
    STATE(18), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [313] = 5,
    ACTIONS(29), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_let,
    ACTIONS(47), 1,
      sym_dedent,
    STATE(21), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [332] = 5,
    ACTIONS(29), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_let,
    ACTIONS(49), 1,
      sym_dedent,
    STATE(21), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [351] = 5,
    ACTIONS(31), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_let,
    ACTIONS(49), 1,
      sym_dedent,
    ACTIONS(51), 1,
      sym_comment,
    STATE(20), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [370] = 5,
    ACTIONS(29), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_let,
    ACTIONS(53), 1,
      sym_dedent,
    STATE(21), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [389] = 5,
    ACTIONS(55), 1,
      sym_comment,
    ACTIONS(58), 1,
      anon_sym_fn,
    ACTIONS(61), 1,
      anon_sym_let,
    ACTIONS(64), 1,
      sym_dedent,
    STATE(21), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [408] = 5,
    ACTIONS(31), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_let,
    ACTIONS(66), 1,
      sym_comment,
    ACTIONS(68), 1,
      sym_dedent,
    STATE(23), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [427] = 5,
    ACTIONS(29), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_let,
    ACTIONS(70), 1,
      sym_dedent,
    STATE(21), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [446] = 5,
    ACTIONS(31), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_let,
    ACTIONS(70), 1,
      sym_dedent,
    ACTIONS(72), 1,
      sym_comment,
    STATE(26), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [465] = 5,
    ACTIONS(31), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_let,
    ACTIONS(74), 1,
      sym_comment,
    ACTIONS(76), 1,
      sym_dedent,
    STATE(27), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [484] = 5,
    ACTIONS(29), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_let,
    ACTIONS(76), 1,
      sym_dedent,
    STATE(21), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [503] = 5,
    ACTIONS(29), 1,
      sym_comment,
    ACTIONS(31), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_let,
    ACTIONS(78), 1,
      sym_dedent,
    STATE(21), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [522] = 5,
    ACTIONS(31), 1,
      anon_sym_fn,
    ACTIONS(33), 1,
      anon_sym_let,
    ACTIONS(78), 1,
      sym_dedent,
    ACTIONS(80), 1,
      sym_comment,
    STATE(12), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [541] = 5,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    ACTIONS(82), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_fn,
    ACTIONS(88), 1,
      anon_sym_let,
    STATE(29), 4,
      sym__statement,
      sym_function_definition,
      sym_let_statement,
      aux_sym_source_file_repeat1,
  [560] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_number,
    ACTIONS(93), 1,
      anon_sym_DQUOTE,
    ACTIONS(95), 1,
      sym_identifier,
    STATE(95), 1,
      sym_expression,
    STATE(112), 2,
      sym_call_expression,
      sym_string,
  [580] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(77), 1,
      sym_expression,
    STATE(68), 2,
      sym_call_expression,
      sym_string,
  [600] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_number,
    ACTIONS(93), 1,
      anon_sym_DQUOTE,
    ACTIONS(95), 1,
      sym_identifier,
    STATE(84), 1,
      sym_expression,
    STATE(112), 2,
      sym_call_expression,
      sym_string,
  [620] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_number,
    ACTIONS(93), 1,
      anon_sym_DQUOTE,
    ACTIONS(95), 1,
      sym_identifier,
    STATE(85), 1,
      sym_expression,
    STATE(112), 2,
      sym_call_expression,
      sym_string,
  [640] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_number,
    ACTIONS(93), 1,
      anon_sym_DQUOTE,
    ACTIONS(95), 1,
      sym_identifier,
    STATE(88), 1,
      sym_expression,
    STATE(112), 2,
      sym_call_expression,
      sym_string,
  [660] = 4,
    ACTIONS(97), 1,
      sym_comment,
    ACTIONS(99), 1,
      anon_sym_DQUOTE,
    STATE(38), 1,
      aux_sym_string_repeat1,
    ACTIONS(101), 2,
      aux_sym_string_token1,
      anon_sym_DQUOTE_DQUOTE,
  [674] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 4,
      anon_sym_RPAREN,
      anon_sym_COLON,
      anon_sym_EQ,
      anon_sym_COMMA,
  [684] = 4,
    ACTIONS(97), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      aux_sym_string_repeat1,
    ACTIONS(107), 2,
      aux_sym_string_token1,
      anon_sym_DQUOTE_DQUOTE,
  [698] = 4,
    ACTIONS(97), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      aux_sym_string_repeat1,
    ACTIONS(107), 2,
      aux_sym_string_token1,
      anon_sym_DQUOTE_DQUOTE,
  [712] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    ACTIONS(113), 1,
      sym_identifier,
    STATE(60), 1,
      sym_parameter,
    STATE(117), 1,
      sym_parameters,
  [728] = 4,
    ACTIONS(97), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      aux_sym_string_repeat1,
    ACTIONS(117), 2,
      aux_sym_string_token1,
      anon_sym_DQUOTE_DQUOTE,
  [742] = 4,
    ACTIONS(97), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_DQUOTE,
    STATE(37), 1,
      aux_sym_string_repeat1,
    ACTIONS(122), 2,
      aux_sym_string_token1,
      anon_sym_DQUOTE_DQUOTE,
  [756] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      sym_identifier,
    ACTIONS(124), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      sym_parameter,
    STATE(116), 1,
      sym_parameters,
  [772] = 1,
    ACTIONS(126), 4,
      sym_dedent,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
  [779] = 1,
    ACTIONS(128), 4,
      sym_dedent,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
  [786] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_LPAREN,
    ACTIONS(132), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [797] = 1,
    ACTIONS(134), 4,
      sym_dedent,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
  [804] = 1,
    ACTIONS(136), 4,
      sym_dedent,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
  [811] = 1,
    ACTIONS(138), 4,
      sym_dedent,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
  [818] = 1,
    ACTIONS(140), 4,
      sym_dedent,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
  [825] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_RPAREN,
    ACTIONS(144), 1,
      anon_sym_COMMA,
    STATE(53), 1,
      aux_sym_arguments_repeat1,
  [838] = 1,
    ACTIONS(146), 4,
      sym_dedent,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
  [845] = 1,
    ACTIONS(136), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
  [852] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 1,
      anon_sym_COMMA,
    ACTIONS(148), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      aux_sym_arguments_repeat1,
  [865] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_RPAREN,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      aux_sym_arguments_repeat1,
  [878] = 1,
    ACTIONS(146), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
  [885] = 1,
    ACTIONS(126), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
  [892] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_RPAREN,
    ACTIONS(157), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_parameters_repeat1,
  [905] = 1,
    ACTIONS(128), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
  [912] = 1,
    ACTIONS(138), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
  [919] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_RPAREN,
    ACTIONS(162), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_parameters_repeat1,
  [932] = 1,
    ACTIONS(134), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
  [939] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_COMMA,
    ACTIONS(164), 1,
      anon_sym_RPAREN,
    STATE(57), 1,
      aux_sym_parameters_repeat1,
  [952] = 1,
    ACTIONS(140), 4,
      ts_builtin_sym_end,
      sym_comment,
      anon_sym_fn,
      anon_sym_let,
  [959] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_COLON,
    ACTIONS(168), 1,
      anon_sym_EQ,
  [969] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_COLON,
    ACTIONS(172), 1,
      anon_sym_EQ,
  [979] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [987] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [995] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1003] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1011] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1019] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1027] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1035] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_newline,
    ACTIONS(184), 1,
      anon_sym_LPAREN,
  [1045] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_DASH_GT,
    ACTIONS(188), 1,
      anon_sym_COLON,
  [1055] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      sym_identifier,
    STATE(67), 1,
      sym_parameter,
  [1065] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_DASH_GT,
    ACTIONS(192), 1,
      anon_sym_COLON,
  [1075] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1083] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      anon_sym_DASH_GT,
    ACTIONS(196), 1,
      anon_sym_COLON,
  [1093] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      anon_sym_DASH_GT,
    ACTIONS(200), 1,
      anon_sym_COLON,
  [1103] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      anon_sym_LPAREN,
  [1110] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym_newline,
  [1117] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
  [1124] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_newline,
  [1131] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      sym_newline,
  [1138] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 1,
      sym_newline,
  [1145] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_COLON,
  [1152] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      sym_indent,
  [1159] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      sym_newline,
  [1166] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_RPAREN,
  [1173] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      sym_identifier,
  [1180] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_newline,
  [1187] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      sym_identifier,
  [1194] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      sym_newline,
  [1201] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      sym_indent,
  [1208] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      sym_newline,
  [1215] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      sym_indent,
  [1222] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      sym_newline,
  [1229] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_EQ,
  [1236] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      sym_newline,
  [1243] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_COLON,
  [1250] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      sym_indent,
  [1257] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      sym_indent,
  [1264] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      sym_indent,
  [1271] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_COLON,
  [1278] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_EQ,
  [1285] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      sym_newline,
  [1292] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      sym_newline,
  [1299] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      sym_newline,
  [1306] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      sym_newline,
  [1313] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 1,
      sym_identifier,
  [1320] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      sym_newline,
  [1327] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      sym_newline,
  [1334] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      ts_builtin_sym_end,
  [1341] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_COLON,
  [1348] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 1,
      anon_sym_COLON,
  [1355] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
  [1362] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
  [1369] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym_indent,
  [1376] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      sym_newline,
  [1383] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_LPAREN,
  [1390] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      sym_identifier,
  [1397] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      sym_indent,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 21,
  [SMALL_STATE(4)] = 42,
  [SMALL_STATE(5)] = 63,
  [SMALL_STATE(6)] = 84,
  [SMALL_STATE(7)] = 105,
  [SMALL_STATE(8)] = 126,
  [SMALL_STATE(9)] = 147,
  [SMALL_STATE(10)] = 173,
  [SMALL_STATE(11)] = 199,
  [SMALL_STATE(12)] = 218,
  [SMALL_STATE(13)] = 237,
  [SMALL_STATE(14)] = 256,
  [SMALL_STATE(15)] = 275,
  [SMALL_STATE(16)] = 294,
  [SMALL_STATE(17)] = 313,
  [SMALL_STATE(18)] = 332,
  [SMALL_STATE(19)] = 351,
  [SMALL_STATE(20)] = 370,
  [SMALL_STATE(21)] = 389,
  [SMALL_STATE(22)] = 408,
  [SMALL_STATE(23)] = 427,
  [SMALL_STATE(24)] = 446,
  [SMALL_STATE(25)] = 465,
  [SMALL_STATE(26)] = 484,
  [SMALL_STATE(27)] = 503,
  [SMALL_STATE(28)] = 522,
  [SMALL_STATE(29)] = 541,
  [SMALL_STATE(30)] = 560,
  [SMALL_STATE(31)] = 580,
  [SMALL_STATE(32)] = 600,
  [SMALL_STATE(33)] = 620,
  [SMALL_STATE(34)] = 640,
  [SMALL_STATE(35)] = 660,
  [SMALL_STATE(36)] = 674,
  [SMALL_STATE(37)] = 684,
  [SMALL_STATE(38)] = 698,
  [SMALL_STATE(39)] = 712,
  [SMALL_STATE(40)] = 728,
  [SMALL_STATE(41)] = 742,
  [SMALL_STATE(42)] = 756,
  [SMALL_STATE(43)] = 772,
  [SMALL_STATE(44)] = 779,
  [SMALL_STATE(45)] = 786,
  [SMALL_STATE(46)] = 797,
  [SMALL_STATE(47)] = 804,
  [SMALL_STATE(48)] = 811,
  [SMALL_STATE(49)] = 818,
  [SMALL_STATE(50)] = 825,
  [SMALL_STATE(51)] = 838,
  [SMALL_STATE(52)] = 845,
  [SMALL_STATE(53)] = 852,
  [SMALL_STATE(54)] = 865,
  [SMALL_STATE(55)] = 878,
  [SMALL_STATE(56)] = 885,
  [SMALL_STATE(57)] = 892,
  [SMALL_STATE(58)] = 905,
  [SMALL_STATE(59)] = 912,
  [SMALL_STATE(60)] = 919,
  [SMALL_STATE(61)] = 932,
  [SMALL_STATE(62)] = 939,
  [SMALL_STATE(63)] = 952,
  [SMALL_STATE(64)] = 959,
  [SMALL_STATE(65)] = 969,
  [SMALL_STATE(66)] = 979,
  [SMALL_STATE(67)] = 987,
  [SMALL_STATE(68)] = 995,
  [SMALL_STATE(69)] = 1003,
  [SMALL_STATE(70)] = 1011,
  [SMALL_STATE(71)] = 1019,
  [SMALL_STATE(72)] = 1027,
  [SMALL_STATE(73)] = 1035,
  [SMALL_STATE(74)] = 1045,
  [SMALL_STATE(75)] = 1055,
  [SMALL_STATE(76)] = 1065,
  [SMALL_STATE(77)] = 1075,
  [SMALL_STATE(78)] = 1083,
  [SMALL_STATE(79)] = 1093,
  [SMALL_STATE(80)] = 1103,
  [SMALL_STATE(81)] = 1110,
  [SMALL_STATE(82)] = 1117,
  [SMALL_STATE(83)] = 1124,
  [SMALL_STATE(84)] = 1131,
  [SMALL_STATE(85)] = 1138,
  [SMALL_STATE(86)] = 1145,
  [SMALL_STATE(87)] = 1152,
  [SMALL_STATE(88)] = 1159,
  [SMALL_STATE(89)] = 1166,
  [SMALL_STATE(90)] = 1173,
  [SMALL_STATE(91)] = 1180,
  [SMALL_STATE(92)] = 1187,
  [SMALL_STATE(93)] = 1194,
  [SMALL_STATE(94)] = 1201,
  [SMALL_STATE(95)] = 1208,
  [SMALL_STATE(96)] = 1215,
  [SMALL_STATE(97)] = 1222,
  [SMALL_STATE(98)] = 1229,
  [SMALL_STATE(99)] = 1236,
  [SMALL_STATE(100)] = 1243,
  [SMALL_STATE(101)] = 1250,
  [SMALL_STATE(102)] = 1257,
  [SMALL_STATE(103)] = 1264,
  [SMALL_STATE(104)] = 1271,
  [SMALL_STATE(105)] = 1278,
  [SMALL_STATE(106)] = 1285,
  [SMALL_STATE(107)] = 1292,
  [SMALL_STATE(108)] = 1299,
  [SMALL_STATE(109)] = 1306,
  [SMALL_STATE(110)] = 1313,
  [SMALL_STATE(111)] = 1320,
  [SMALL_STATE(112)] = 1327,
  [SMALL_STATE(113)] = 1334,
  [SMALL_STATE(114)] = 1341,
  [SMALL_STATE(115)] = 1348,
  [SMALL_STATE(116)] = 1355,
  [SMALL_STATE(117)] = 1362,
  [SMALL_STATE(118)] = 1369,
  [SMALL_STATE(119)] = 1376,
  [SMALL_STATE(120)] = 1383,
  [SMALL_STATE(121)] = 1390,
  [SMALL_STATE(122)] = 1397,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(121),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(110),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_annotation, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [117] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 5, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 7, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 9, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 10, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 11, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 12, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 8, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arguments, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arguments_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0),
  [157] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 1, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 4, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [260] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_newline = 0,
  ts_external_token_indent = 1,
  ts_external_token_dedent = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_newline] = sym_newline,
  [ts_external_token_indent] = sym_indent,
  [ts_external_token_dedent] = sym_dedent,
};

static const bool ts_external_scanner_states[5][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_newline] = true,
    [ts_external_token_indent] = true,
    [ts_external_token_dedent] = true,
  },
  [2] = {
    [ts_external_token_dedent] = true,
  },
  [3] = {
    [ts_external_token_newline] = true,
  },
  [4] = {
    [ts_external_token_indent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_nyx_external_scanner_create(void);
void tree_sitter_nyx_external_scanner_destroy(void *);
bool tree_sitter_nyx_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_nyx_external_scanner_serialize(void *, char *);
void tree_sitter_nyx_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nyx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_nyx_external_scanner_create,
      tree_sitter_nyx_external_scanner_destroy,
      tree_sitter_nyx_external_scanner_scan,
      tree_sitter_nyx_external_scanner_serialize,
      tree_sitter_nyx_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "nyx",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
